name: Build & Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        if: success()
        run: docker build -t mrbenosborne/go-http-cache:latest .

      - name: Push to docker hub :latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push mrbenosborne/go-http-cache:latest
